### ISSUE TITLE
Link this middleware on hono.dev

### ISSUE THREAD

**Issue by marcomuser** [maou-shonen/hono-simple-DI#15]
Hi. I just came across this middleware completely by accident. Github happened to suggest it in my feed. I love how easy service injection is with this middleware and how much boilerplate code it allows me to delete. Would you mind if we add a link for this tiny but amazing middleware on [hono.dev](https://hono.dev/docs/middleware/third-party)? Or maybe even considered if it would find a wider audience in hono's third-party [middleware repo](https://github.com/honojs/middleware)? The documentation on dependency injection with Hono is currently still somewhat limited. If this middleware could be found more easily, it would certainly help many people to get up to speed with Hono and figure out how to achieve simple dependency injection with it's context api.

Thanks a lot for publishing it! ❤️

**Comment by maou-shonen** [comment]
Hi! I'm glad you like this package.

I'm publishing it in my repository rather than through `hono middleware repo`, because I use it extensively in my company's projects, and I need fast to develop and release updates. That said, I'm definitely open to feature requests and bug fixes.

As for why it’s not link to hono.dev, it’s because my English isn’t great, and I’m not confident enough to ensure the documentation would be clear and understandable for everyone. However, if you find this library helpful, it's welcome.

**Comment by marcomuser** [comment]
That makes perfect sense! 👍  For me, the documentation is perfectly clear and well written. I'm also happy to help work on it if any questions arise. If you don't mind, I'll add a simple link to the hono.dev page I mentioned. I think others will appreciate it.

**Comment by maou-shonen** [comment]
Alright! welcome!

**Comment by maou-shonen** [comment]
I saw that it has already appeared on hono.dev.
Thank you for your appreciation of this package, and happy coding!
